---
title       : Reproducible Research and Collaboration
subtitle    : Fun with markdown and git
author      : Ted Hart & Scott Chamberlain
job         : 
logo        : "ropensci_small.png"
biglogo     : "ropensci_main.png"
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : []            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
assets      :
  css: "http://netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css"
---

## Markdown

> + Markdown, MD for short, is a markup language with a few killer attributes 
  + Super simple to learn (much easier than LaTeX)
  + Incorporate code blocks <i class="icon-code"></i>
  + Allows you to write reproducible documents (code + text)
> + Background
  + Created by [John Gruber](http://daringfireball.net/) (w/ help from [Aaron Swartz](http://www.aaronsw.com/))
  + [The canonical place to learn more](http://daringfireball.net/projects/markdown/)


---

## Markdown use cases

Why would you want to use Markdown?

> + Taking notes
> + Blog posts
> + Research paper
> + MD is used in many places (StackOverflow, Github, etc.), so good to learn it

---

## Markdown - Syntax

> + Headings (#, =, or -)
  + Heading 1 (#)
  + Heading 3 (###)
> + Blockquote (>)
> + Lists
  + Create list using *, +, or -, or ordered list using 1., 2., etc.
  + Nested lists, and more, see the MD site
> + Code blocks
  + Indent 1 tab or 4 spaces
> + Emphasis
  + __Bold__ \*\*bold\*\* or \_\_bold\_\_
  + _Italic_ *italic* or \_italic\_
  + In the middle of a world: un\*\*believe\*\*able
> + Links, like this => []() or [][] with []: url somewhere else
> + You can always just write html!

---

## Markdown - your turn

<i class="icon-exclamation-sign"></i> Exercizes!

1. Write some simple markdown. View it in your favorite MD viewer.
2. Write markdown with code blocks that execute code using R. Compile the file and view.

---

## git

> + git is a version control system
> + Use cases
  + Local version control of some files
  + Branching to try out completely new things
  + Collaboration with others
  + Forking!


---

## git - your turn

> + If you have git installed, and/or a git GUI:
  + Create a folder
  + Create a document inside that folder with some markdown text
  + Commit those changes
  + Make some additional changes to your file
  + Commit those changes
  + Create a branch
  + Make a few changes to the file on the new branch
  + Merge the new branch into the master branch

---

## Resources

> + stuff and things